### ISSUE TITLE
Renaming plugin to match multiple CSS Preprocessors

### ISSUE THREAD

**Issue by DennisBecker** [DennisBecker/grunt-sass-globbing#11]
After some testing and reading documentations I've seen that this plugin also works out-of-the-box with different CSS preprocessors. I have created it to use it with Grunt / libsass, but it also works well with Less or PostCSS.

I'm unsure if this plugin should be renamed to clearify, that it also works well with the other preprocessors.

It would be nice if you comment on this issue with +1 for renaming or -1 on not renaming this plugin.

**Comment by DennisBecker** [comment]
+1

**Comment by heaper** [comment]
+1

**Comment by aladage** [comment]
+1

**Comment by krisbulman** [comment]
+1

**Comment by DennisBecker** [comment]
I'll see a lot of downloads and I think renaming this plugin would be a pain for a lot of people, so renaming is not an option.
