### ISSUE TITLE
Wrong relative paths

### ISSUE THREAD

**Issue by Regaddi** [DennisBecker/grunt-sass-globbing#27]
Hi,

after updating to 1.5.0 I've encountered an issue with generated relative paths outside the current directory.

Given the following directory structure

    assets
        - components
            - someModule
                - somemodule.variables.scss
        - scss
            - variables

and the following grunt task configuration

    module.exports = function(grunt) {
      'use strict';
      return grunt.config.set('sass_globbing', {
        dist: {
          options: {
            useSingleQuotes: true
          },
          files: {
            'assets/scss/variables/_components.scss': 'assets/components/**/*.variables.scss'
          }
        }
      });
    };

I get the following generated `_components.scss file`

    /* generated with grunt-sass-globbing */

    @import '..components/someModule/somemodule.variables';

which is definitely a wrong path.

Using version 1.4.0 I get the correct assumed file output:

    /* generated with grunt-sass-globbing */

    @import '../../components/someModule/somemodule.variables';

**Comment by pedrosanta** [comment]
+1, I'm also getting this one. 😕

**Comment by DennisBecker** [comment]
Thanks for reporting the issue, I'm currently at work but will look into it at lunch time in about an hour. First I'll add a test to reproduce your reported behaviour

**Comment by pedrosanta** [comment]
@DennisBecker 👍

**Comment by DennisBecker** [comment]
Okay, I have found the problem, it was introduced with the pull request #18 - I have a test to reproduce this issue and will now create a patch release.

**Comment by DennisBecker** [comment]
v1.5.1 is released

**Comment by Regaddi** [comment]
Tested. Works. Thank you very much :+1: :smiley:
