### ISSUE TITLE
Nested import duplicating selector

### ISSUE THREAD

**Issue by ethikz** [DennisBecker/grunt-sass-globbing#29]
Has anyone noticed this issue before or is there something I am missing?  This could also be a grunt-sass issue as well.  I haven't quite figured it out yet.

I have this example scss:
`.class {
  @import "../../variables-global";
}`

What I expect to see output is:
`.class {
  color: #f00;
}`

What is actually being outputted by sass_globbing
`.class {
   .class {
      color: #f00;
   }
}`

**Comment by DennisBecker** [comment]
I'm sorry to tell you that but it seems you have reported this issue for an other grunt plugin or npm module. grunt-sass-globbing does not modify files in place, it creates a new file which you can import in your code.

**Comment by ethikz** [comment]
Thanks for letting me know.  I'll look more into it
