### ISSUE TITLE
Works great thanks!

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [DennisBecker/grunt-sass-globbing#7]
I've been wanting to use Libsass for a while now and I couldn't because I read that it was not yet compatible with globbing & breakpoint which I like both a lot. Thanks to Zell's article http://www.zell-weekeat.com/grunt-sass-with-susy/ I realized I could use Breakpoint as a bower component. The only missing piece was globbing and thanks to you I'm all set to play with my new toys now :)

**Comment by DennisBecker** [comment]
Thank you very much!

I built this little grunt plugin to migrate projects at work from Ruby Sass to Libsass and also give flexibility on the usage in comparison to other solutions which didn't fit.

If you have any idea just open an issue and I'll check if it's worth implementing - or just open a pull request ;)
