### ISSUE TITLE
Non-compliant comment at top of the destination file

### ISSUE THREAD

**Issue by heaper** [DennisBecker/grunt-sass-globbing#8]
Any chance you can change the **//generated with grunt-sass-globbing** comment that gets added to the top of the destination file to be CSS compliant? Specifically, **/* generated with grunt-sass-globbing */**.  I'm using grunt-sass-globbing in conjunction with postcss (rather than SASS), and the postcss processor gets hung-up on the non-compliant comment. Thanks!

**Comment by DennisBecker** [comment]
I didn't know PostCSS before.

If this plugin works with PostCSS I will change the comment style so that it works also out of the box with PostCSS. But I'm really busy at the moment so this will be changed next week after 9th March.

**Comment by DennisBecker** [comment]
Fixed in new version 1.2.0.
